// Shared silhouettes for equipment kind builders. Every helper draws into the CURRENT PrimBuilder frame
// (local coordinates, y = 0 floor). Positions are footprint CENTRES unless noted; `ry` is degrees.
// Add your own helpers in your own files — do not edit this file.
import type { PrimBuilder } from './prims';
import { BRAND, SCENE } from './palette';

export const STEEL = SCENE.stainless; // #c7d0d8
export const STEEL_DARK = SCENE.stainlessDark; // #9aa7b2
export const STEEL_MID = '#b3bec8';
export const CHARCOAL = '#3a4349';
export const FOLIAGE_OLIVE = SCENE.foliageOlive; // #8f854a
export const FOLIAGE_GREEN = SCENE.foliageGreen; // #5f8f4f

type At = { x?: number; z?: number; y?: number; ry?: number };

function at(b: PrimBuilder, o: At, fn: () => void) {
  if (o.x || o.z || o.y || o.ry) b.frame({ x: o.x, y: o.y, z: o.z, ry: o.ry }, fn);
  else fn();
}

/** Stainless work bench: top, front apron, four legs and an undershelf. Default height 3 ft. */
export function bench(b: PrimBuilder, o: At & { w: number; d: number; h?: number; shelf?: boolean; splash?: boolean; top?: string }) {
  const h = o.h ?? 3;
  at(b, o, () => {
    const t = 0.12;
    b.box({ m: 'steel', c: o.top ?? STEEL, y: h - t, w: o.w, h: t, d: o.d });
    b.box({ m: 'steel', c: STEEL_DARK, y: h - t - 0.35, w: o.w - 0.1, h: 0.35, d: 0.06, z: o.d / 2 - 0.1 });
    const lx = o.w / 2 - 0.1, lz = o.d / 2 - 0.1;
    for (const sx of [-1, 1]) for (const sz of [-1, 1]) {
      b.box({ m: 'steel', c: STEEL_DARK, x: sx * lx, z: sz * lz, w: 0.1, h: h - t, d: 0.1 });
    }
    if (o.shelf !== false) b.box({ m: 'steel', c: STEEL_DARK, y: 0.6, w: o.w - 0.2, h: 0.07, d: o.d - 0.2 });
    if (o.splash) b.box({ m: 'steel', c: STEEL, y: h, z: -o.d / 2 + 0.05, w: o.w, h: 0.55, d: 0.1 });
  });
}

/** Round colour-coded bin with lid. Height h (default 2.4). */
export function bin(b: PrimBuilder, o: At & { r?: number; h?: number; c: string; lid?: string }) {
  const r = o.r ?? 0.7, h = o.h ?? 2.4;
  at(b, o, () => {
    b.cyl({ m: 'gloss', c: o.c, r, h: h - 0.12 });
    b.cyl({ m: 'gloss', c: o.lid ?? o.c, r: r + 0.04, y: h - 0.12, h: 0.14 });
    b.box({ m: 'matte', c: '#2b3236', y: h + 0.02, w: 0.35, h: 0.06, d: 0.08, shadow: false });
  });
}

/** Stackable crate (w × d × h). */
export function crate(b: PrimBuilder, o: At & { w?: number; d?: number; h?: number; c?: string }) {
  const w = o.w ?? 1.6, d = o.d ?? 1.1, h = o.h ?? 0.9;
  at(b, o, () => {
    b.box({ m: 'matte', c: o.c ?? '#b9854a', w, h, d });
    b.box({ m: 'matte', c: '#8f6535', y: h * 0.45, w: w + 0.02, h: 0.08, d: d + 0.02, shadow: false });
  });
}

export function stool(b: PrimBuilder, o: At & { h?: number; c?: string }) {
  const h = o.h ?? 2.1;
  at(b, o, () => {
    b.cyl({ m: 'matte', c: o.c ?? BRAND.teal, r: 0.55, y: h - 0.2, h: 0.2 });
    b.cyl({ m: 'steel', c: STEEL_DARK, r: 0.08, h: h - 0.2 });
    b.cyl({ m: 'steel', c: STEEL_DARK, r: 0.4, h: 0.06 });
  });
}

/** Round table. */
export function roundTable(b: PrimBuilder, o: At & { r?: number; h?: number; top?: string }) {
  const r = o.r ?? 1.6, h = o.h ?? 2.5;
  at(b, o, () => {
    b.cyl({ m: 'gloss', c: o.top ?? BRAND.cream, r, y: h - 0.14, h: 0.14 });
    b.cyl({ m: 'steel', c: STEEL_DARK, r: 0.12, h: h - 0.14 });
    b.cyl({ m: 'steel', c: STEEL_DARK, r: 0.6, h: 0.08 });
  });
}

/** Potted plant: terracotta pot + 3 foliage blobs (olive and green mix). */
export function plant(b: PrimBuilder, o: At & { s?: number; pot?: string }) {
  const s = o.s ?? 1;
  at(b, o, () => {
    b.cyl({ m: 'matte', c: o.pot ?? BRAND.orange, r: 0.38 * s, h: 0.7 * s });
    b.cyl({ m: 'matte', c: '#7a4a2a', r: 0.34 * s, y: 0.66 * s, h: 0.06 * s, shadow: false });
    b.sph({ m: 'matte', c: FOLIAGE_OLIVE, r: 0.5 * s, x: 0, y: 1.25 * s, z: 0, sy: 1.15 });
    b.sph({ m: 'matte', c: FOLIAGE_GREEN, r: 0.38 * s, x: 0.28 * s, y: 1.6 * s, z: 0.1 * s });
    b.sph({ m: 'matte', c: FOLIAGE_OLIVE, r: 0.34 * s, x: -0.26 * s, y: 1.5 * s, z: -0.12 * s });
  });
}

/** Small indoor tree: trunk + layered olive/green canopy. h = overall height. */
export function tree(b: PrimBuilder, o: At & { h?: number; r?: number }) {
  const h = o.h ?? 6, r = o.r ?? 1.5;
  at(b, o, () => {
    b.cyl({ m: 'matte', c: '#6b4a32', r: 0.14, h: h * 0.55 });
    b.sph({ m: 'matte', c: FOLIAGE_OLIVE, r, x: 0, y: h * 0.7, z: 0, sy: 0.85 });
    b.sph({ m: 'matte', c: FOLIAGE_GREEN, r: r * 0.7, x: r * 0.55, y: h * 0.85, z: r * 0.2, sy: 0.9 });
    b.sph({ m: 'matte', c: FOLIAGE_GREEN, r: r * 0.62, x: -r * 0.5, y: h * 0.8, z: -r * 0.25, sy: 0.9 });
    b.sph({ m: 'matte', c: FOLIAGE_OLIVE, r: r * 0.5, x: 0, y: h * 0.97, z: 0, sy: 0.9 });
  });
}

/**
 * Steel shelving bay: four posts and `levels` shelves, optionally loaded with crates.
 * Footprint w × d, height h (default 6.5).
 */
export function shelfBay(b: PrimBuilder, o: At & { w: number; d: number; h?: number; levels?: number; load?: boolean; seed?: number }) {
  const h = o.h ?? 6.5, n = o.levels ?? 4;
  at(b, o, () => {
    const px = o.w / 2 - 0.06, pz = o.d / 2 - 0.06;
    for (const sx of [-1, 1]) for (const sz of [-1, 1]) b.box({ m: 'steel', c: STEEL_DARK, x: sx * px, z: sz * pz, w: 0.12, h, d: 0.12 });
    let k = o.seed ?? 1;
    const rnd = () => ((k = (k * 16807) % 2147483647) / 2147483647);
    for (let i = 0; i < n; i++) {
      const y = 0.35 + (i * (h - 0.6)) / (n - 1 || 1);
      b.box({ m: 'steel', c: STEEL, y, w: o.w - 0.08, h: 0.07, d: o.d - 0.08 });
      if (o.load) {
        const cw = 0.9 + rnd() * 0.5;
        const cnt = Math.max(1, Math.floor((o.w - 0.3) / (cw + 0.12)));
        for (let j = 0; j < cnt; j++) {
          const x = -o.w / 2 + 0.2 + cw / 2 + j * (cw + 0.12);
          b.box({ m: 'matte', c: rnd() > 0.5 ? '#b9854a' : '#cba269', x, y: y + 0.07, w: cw, h: 0.55 + rnd() * 0.3, d: Math.min(o.d - 0.3, 1.1) });
        }
      }
    }
  });
}

/** Wall-mounted shelf (a long thin board on brackets). Local z=0 is the shelf centre; mount against a wall by placing the frame at the wall. */
export function wallShelf(b: PrimBuilder, o: At & { w: number; d?: number; h?: number; c?: string }) {
  const d = o.d ?? 0.7;
  at(b, o, () => {
    b.box({ m: 'steel', c: o.c ?? STEEL, y: o.h ?? 5, w: o.w, h: 0.08, d });
    for (const sx of [-1, 1]) b.box({ m: 'steel', c: STEEL_DARK, x: sx * (o.w / 2 - 0.3), y: (o.h ?? 5) - 0.3, z: -d / 2 + 0.05, w: 0.06, h: 0.3, d: 0.06, shadow: false });
  });
}

/** Tall fridge/freezer, front faces +z. */
export function fridge(b: PrimBuilder, o: At & { w?: number; d?: number; h?: number; c?: string; doors?: number }) {
  const w = o.w ?? 2.4, d = o.d ?? 2.4, h = o.h ?? 6.5, n = o.doors ?? 1;
  at(b, o, () => {
    b.box({ m: 'steel', c: o.c ?? STEEL, w, h, d });
    for (let i = 0; i < n; i++) {
      const dh = (h - 0.4) / n;
      b.box({ m: 'steel', c: o.c ?? STEEL_MID, y: 0.2 + i * dh + 0.02, z: d / 2 + 0.02, w: w - 0.12, h: dh - 0.06, d: 0.05 });
      b.box({ m: 'steel', c: STEEL_DARK, x: w / 2 - 0.3, y: 0.2 + i * dh + dh * 0.45, z: d / 2 + 0.1, w: 0.07, h: dh * 0.35, d: 0.06, shadow: false });
    }
    b.box({ m: 'matte', c: '#3a4349', y: 0, w: w + 0.02, h: 0.2, d: d + 0.02, shadow: false });
  });
}
